[package]
name = "TestRust"
version = "0.1.0"
authors = ["박기현 <t2006036@partner.coway.co.kr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
